### ISSUE TITLE
Torch 1.7 complains about Tensor resize

### ISSUE THREAD

**Issue by sans-sense** [zengyan-97/Transformer-DST#1]
On torch 1.7, the  run command ```sh -x ./run_train_dt.sh``` fails as train.py tries changing bert token type count from 2 to 4.

Actual error message
Trying to resize storage that is not resizable, THStorageFunctions.cpp:87 

Not sure if it is torch build or if resizing is frowned upon in new torch. Workaround was creating a new tensor.

Workaround, fallback on explicitly cloning the tensor clone and stacking them solves it
<pre>
    try:
        state_dict[_k].resize_(
            type_vocab_size, state_dict[_k].shape[1])
        state_dict[_k].data[2, :].copy_(state_dict[_k].data[0, :])
        state_dict[_k].data[3, :].copy_(state_dict[_k].data[0, :])
    except:
        tgt_tensor  = state_dict[_k]
        token_0_tensor = tgt_tensor[0, :]
        new_token_embb = torch.stack([token_0_tensor, tgt_tensor[1, :], token_0_tensor.clone(), token_0_tensor.clone()])
        state_dict[_k] = new_token_embb
</pre>

**Comment by zengyan-97** [comment]
Thanks for the patch : )
