### ISSUE TITLE
ValueError: expected sequence of length

### ISSUE THREAD

**Issue by dzy1011** [zengyan-97/Transformer-DST#2]
When batch_size>1, the following error will occur:

File "/home/Transformer-DST-main/utils/data_utils.py", line 586, in wrap_into_tensor

     state_position_ids = torch.tensor(slot_position, dtype=torch.long)

ValueError: expected sequence of length 62 at dim 1 (got 60)

    The length of the list in slot_position is different.

**Comment by zengyan-97** [comment]
Which command did you run? I am running the training script, and it goes well till now.

**Comment by rohit129** [comment]
Hi.. when running the model for "bert-base-multilingual-uncased" using files downloaded from the link below: 

1) model file: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-pytorch_model.bin" 
2) vocab file: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-vocab.txt"
3) config file: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-config.json"

The model is giving error:

`Traceback (most recent call last):
  File "train.py", line 456, in <module> main(args)

  File "train.py", line 292, in main
    for step, batch in enumerate(train_dataloader):
  File "/home/naive/.conda/envs/torch_gpu36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/naive/.conda/envs/torch_gpu36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/naive/Documents/rohit/DST/HINDI_MWOZ/models/transformer_dst/Transformer-DST/utils/data_utils.py", line 451, in collate_fn
    use_cls_only=self.use_cls_only)
  File "/home/naive/Documents/rohit/DST/HINDI_MWOZ/models/transformer_dst/Transformer-DST/utils/data_utils.py", line 581, in wrap_into_tensor
    state_position_ids = torch.tensor(slot_position, dtype=torch.long)
ValueError: expected sequence of length 30 at dim 1 (got 27)
`

Will this code work in this "bert-base-multilingual-uncased" setting ?

**Comment by zengyan-97** [comment]
> Hi.. when running the model for "bert-base-multilingual-uncased" using files downloaded from the link below:
> 
> 1. model file: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-pytorch_model.bin"
> 2. vocab file: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-vocab.txt"
> 3. config file: "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-config.json"
> 
> The model is giving error:
> 
> `Traceback (most recent call last): File "train.py", line 456, in main(args)
> 
> File "train.py", line 292, in main for step, batch in enumerate(train_dataloader): File "/home/naive/.conda/envs/torch_gpu36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in **next** data = self.dataset_fetcher.fetch(index) # may raise StopIteration File "/home/naive/.conda/envs/torch_gpu36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch return self.collate_fn(data) File "/home/naive/Documents/rohit/DST/HINDI_MWOZ/models/transformer_dst/Transformer-DST/utils/data_utils.py", line 451, in collate_fn use_cls_only=self.use_cls_only) File "/home/naive/Documents/rohit/DST/HINDI_MWOZ/models/transformer_dst/Transformer-DST/utils/data_utils.py", line 581, in wrap_into_tensor state_position_ids = torch.tensor(slot_position, dtype=torch.long) ValueError: expected sequence of length 30 at dim 1 (got 27) `
> 
> Will this code work in this "bert-base-multilingual-uncased" setting ?

Hi, the code cannot be directly applied to multilingual settings. You need to modify the code yourself. 
Sorry for my late reply...
