### ISSUE TITLE
Inquiries about Input IDs

### ISSUE THREAD

**Issue by Bosheng2020** [zengyan-97/Transformer-DST#3]
Hi Zeng Yan,

I have a question on the training part. I have printed the input_ids and also converted the input_ids and I am a bit confused.

Here is the input_IDs:
input_ids[i] tensor([  101,   100,  2053,  2800, 21725,  2015,  2747,  1012,  2052,  2017,
         2066,   100,  2000,  2338,  2242,  2842,  1029,  1025,  3531,  5454,
         2178, 23766,  4113,  4580,  1999,  1996,  2168,  2181,  1012,   102,
         1045,  2572,  3374,   100,   100,  3504,  2066,  2045,  2024,  2053,
         3309,  1011,  1055,   100,  4113, 15666,  9844,  2008,  9181,  1999,
          100,  2225,   100,  2079,  2017,   100,  2178,  2181,  1999,  2568,
         1029,  1025,  3100,  1010,  2672,  1045,  2323,  4088,  2153,   100,
         1045,  2572,  2559,  2005,  1037,  4113,  4580,  1999,  1996,  2167,
         1012,  2024,  2045,  2151,  2800,  1029,   102,     1,  8432,  2181,
         1011,  2225,     1,  8432,  2171,  1011,     2,     1,  8432,  2828,
         1011,  2267,     1,  3309,  2181,  1011,  2225,     1,  3309,  2338,
         2154,  1011,     2,     1,  3309,  2338,  2111,  1011,     2,     1,
         3309,  2338,  2994,  1011,     2,     1,  3309,  4274,  1011,     2,
            1,  3309,  2171,  1011,     2,     1,  3309,  5581,  1011,     2,
            1,  3309,  3976, 24388,  2063,  1011, 10036,     1,  3309,  3340,
         1011,     2,     1,  3309,  2828,  1011,  4113,  2160,     1,  4825,
         2181,  1011,     2,     1,  4825,  2338,  2154,  1011,     2,     1,
         4825,  2338,  2111,  1011,     2,     1,  4825,  2338,  2051,  1011,
            2,     1,  4825,  2833,  1011,     2,     1,  4825,  2171,  1011,
            2,     1,  4825,  3976, 24388,  2063,  1011,     2,     1, 10095,
         7180,  3762,  1011,     2,     1, 10095,  6712,  1011,     2,     1,
        10095,  7688,  1011,     2,     1, 10095,  2681,  4017,  1011,     2,
            1,  3345,  7180,  3762,  1011,     2,     1,  3345,  2338,  2111,
         1011,     2,     1,  3345,  2154,  1011,     2,     1,  3345,  6712,
         1011,     2,     1,  3345,  7688,  1011,     2,     1,  3345,  2681,
         4017,  1011,     2])

And here are the results converted from input_ids to tokens:

['[CLS]', '[UNK]', 'no', 'available', 'booking', '##s', 'currently', '.', 'would', 'you', 'like', '[UNK]', 'to', 'book', 'something', 'else', '?', ';', 'please', 'choose', 'another', 'inexpensive', 'guest', '##house', 'in', 'the', 'same', 'area', '.', '[SEP]', 'i', 'am', 'sorry', '[UNK]', '[UNK]', 'looks', 'like', 'there', 'are', 'no', 'hotel', '-', 's', '[UNK]', 'guest', '##houses', 'matching', 'that', 'criteria', 'in', '[UNK]', 'west', '[UNK]', 'do', 'you', '[UNK]', 'another', 'area', 'in', 'mind', '?', ';', 'okay', ',', 'maybe', 'i', 'should', 'begin', 'again', '[UNK]', 'i', 'am', 'looking', 'for', 'a', 'guest', '##house', 'in', 'the', 'north', '.', 'are', 'there', 'any', 'available', '?', '[SEP]', '[SLOT]', 'attraction', 'area', '-', 'west', '[SLOT]', 'attraction', 'name', '-', '[NULL]', '[SLOT]', 'attraction', 'type', '-', 'college', '[SLOT]', 'hotel', 'area', '-', 'west', '[SLOT]', 'hotel', 'book', 'day', '-', '[NULL]', '[SLOT]', 'hotel', 'book', 'people', '-', '[NULL]', '[SLOT]', 'hotel', 'book', 'stay', '-', '[NULL]', '[SLOT]', 'hotel', 'internet', '-', '[NULL]', '[SLOT]', 'hotel', 'name', '-', '[NULL]', '[SLOT]', 'hotel', 'parking', '-', '[NULL]', '[SLOT]', 'hotel', 'price', '##rang', '##e', '-', 'cheap', '[SLOT]', 'hotel', 'stars', '-', '[NULL]', '[SLOT]', 'hotel', 'type', '-', 'guest', 'house', '[SLOT]', 'restaurant', 'area', '-', '[NULL]', '[SLOT]', 'restaurant', 'book', 'day', '-', '[NULL]', '[SLOT]', 'restaurant', 'book', 'people', '-', '[NULL]', '[SLOT]', 'restaurant', 'book', 'time', '-', '[NULL]', '[SLOT]', 'restaurant', 'food', '-', '[NULL]', '[SLOT]', 'restaurant', 'name', '-', '[NULL]', '[SLOT]', 'restaurant', 'price', '##rang', '##e', '-', '[NULL]', '[SLOT]', 'taxi', 'arrive', '##by', '-', '[NULL]', '[SLOT]', 'taxi', 'departure', '-', '[NULL]', '[SLOT]', 'taxi', 'destination', '-', '[NULL]', '[SLOT]', 'taxi', 'leave', '##at', '-', '[NULL]', '[SLOT]', 'train', 'arrive', '##by', '-', '[NULL]', '[SLOT]', 'train', 'book', 'people', '-', '[NULL]', '[SLOT]', 'train', 'day', '-', '[NULL]', '[SLOT]', 'train', 'departure', '-', '[NULL]', '[SLOT]', 'train', 'destination', '-', '[NULL]', '[SLOT]', 'train', 'leave', '##at', '-', '[NULL]']

I have traced back the original training data and I found that the original utterance is "there are no available bookings currently . would you like me to book something else ?". My question is why the two tokens "there" and "are" are missing and it started with  '[CLS]' and '[UNK]' instead of 'there' and 'are'. I also printed some instances and I found some instances aligned with the training data and some didn't. 

May I know what's the reason?

Thanks a lot.

Best regards,

Bosheng

**Comment by zengyan-97** [comment]
Hi!
Would you mind having the same test on this code: https://github.com/clovaai/som-dst? 
I implemented our code based on it, and I did not modify or have a detailed check on the input module.
