### ISSUE TITLE
Error while running sh -x ./run_train_dt.sh

### ISSUE THREAD

**Issue by imvansh25** [zengyan-97/Transformer-DST#5]
Traceback (most recent call last):
  File "train.py", line 456, in <module>
    main(args)
  File "train.py", line 209, in main
    state_dict[_k].resize_(
RuntimeError: Trying to resize storage that is not resizable at /pytorch/aten/src/TH/THStorageFunctions.cpp:100

**Comment by YeJinPaark** [comment]
I have same issue
Did you fix it?
