### ISSUE TITLE
---RuntimeError--- attention_scores torch.Size([16, 12, 256, 256]) attention_mask torch.Size([16, 1, 1, 256])

### ISSUE THREAD

**Issue by peiwenhuang27** [zengyan-97/Transformer-DST#6]
Hi,
I was test running the repo by using git clone, without modifying any of the code, after `sh -x ./run_get_data.sh`, I encountered the following error during `sh -x ./run_train_dt.sh`:
```
...
prepare 7800/8420
prepare 8000/8420
prepare 8200/8420
prepare 8400/8420
### decoder_teacher_forcing: 1
# train examples 54984
prepare 200/1000
prepare 400/1000
prepare 600/1000
prepare 800/1000
prepare 1000/1000
# dev examples 7371
### word index of '-',  1011
start download bert-base-uncased from huggingface
config.type_vocab_size != state_dict[bert.embeddings.token_type_embeddings.weight] (4 != 2)

### Done Load BERT
### Use One Optim
---RuntimeError---
attention_scores torch.Size([16, 12, 256, 256])
attention_mask torch.Size([16, 1, 1, 256])
```

Apparently `attention_scores` and `attention_mask` have different shapes, I wonder which part went wrong that caused the error to happen? Thank you.

**Comment by peiwenhuang27** [comment]
I found out that the cause of the error was actually not due to the shape of tensor, but rather that `attention_mask` is of `torch.int64` type while `attention_scores` is of `torch.float32`. Looks like `attention_mask` has already been expanded to `[16, 1, 1, 256]` that is to be broadcast automatically by PyTorch, but CUDA has problem adding two tensors of different types together.

By adding a type conversion line in `modeling_bert.py, line 324`:
```
attention_mask = attention_mask.type(torch.float32) 
```
the problem will be mitigated.

Is my guess correct? If so, should I close the issue and create a PR? Thank you!

**Comment by qin2021** [comment]
我也碰到了这个问题，请问解决了吗？

**Comment by qin2021** [comment]
你的环境是他要求的torch1.5吗，如果不是，那可能是因为pytorch的版本太低导致的。我从torch1.0.1升级到torch1.5就可以运行了

**Comment by zengyan-97** [comment]
> 

Thanks for your reply! 
Please follow the Requirements to avoid these issues.
